# Generated by Django 3.2.7 on 2023-08-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('date_created', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('color', models.CharField(max_length=123)),
                ('year', models.PositiveIntegerField(default=0)),
                ('max_speed', models.PositiveIntegerField(default=0)),
                ('horse_power', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carmark')),
            ],
        ),
    ]
