# Generated by Django 3.2.7 on 2023-08-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModels',
            new_name='CarModel',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='car',
            new_name='cars',
        ),
    ]
